import { App, requestUrl, Notice, TFile } from 'obsidian';
import { decideSyncAction, encodeQueryValue, getFileRoomName, normalizeServerUrl } from './syncProtocol';

export interface FileManifest {
  [filePath: string]: {
    size: number;
    mtime: number;
    hash?: string;
    deleted?: boolean;
    device?: string;
  };
}

/**
 * Filter mechanism to ignore temporary, transient, or large system files that 
 * cause conflict spam or should not be synced.
 */
function shouldIgnore(path: string): boolean {
  const normalized = path.replace(/\\/g, '/');
  
  // Ephemeral/System directories
  if (
    normalized.startsWith('.git/') || normalized === '.git' ||
    normalized.startsWith('.trash/') || normalized === '.trash' ||
    normalized.startsWith('node_modules/') || normalized === 'node_modules' ||
    normalized.startsWith('.obsidian/plugins/') || normalized === '.obsidian/plugins' ||
    normalized.startsWith('Sync Conflicts/') || normalized === 'Sync Conflicts'
  ) {
    return true;
  }

  // Conflict copy files (generated by previous sync versions)
  if (normalized.includes('(Conflict from ')) {
    return true;
  }

  // Specific noise files and device-specific workspace configurations
  if (
    normalized.includes('.obsidian/workspace') || // covers workspace.json, workspace-mobile.json, workspaces.json, etc.
    normalized.endsWith('/.DS_Store') || normalized === '.DS_Store' ||
    normalized.endsWith('/thumbs.db') || normalized === 'thumbs.db'
  ) {
    return true;
  }

  return false;
}

export class ConfigSyncEngine {
  private isSyncing = false;
  private syncPending = false;
  private syncStateLoadPromise: Promise<void> | null = null;
  private syncStateSavePromise: Promise<void> = Promise.resolve();
  private syncState: Record<string, Record<string, string>> = {};
  private syncStateDirty = false;

  constructor(
    private app: App,
    public serverUrl: string,
    private user: string,
    public pass: string,
    public workspace: string = 'default-workspace',
    private deviceName: string = 'Unknown Device',
    private isLivePath: (path: string) => boolean = () => false,
    private dataDir: string = '.obsidian/plugins/laplas-cowork/data'
  ) {}

  private getQuery(relativePath?: string): string {
    const values = [
      `user=${encodeQueryValue(this.user)}`,
      `pass=${encodeQueryValue(this.pass)}`,
      `workspace=${encodeQueryValue(this.workspace)}`
    ];
    if (relativePath !== undefined) {
      values.push(`path=${encodeQueryValue(relativePath)}`);
      values.push(`room=${encodeQueryValue(getFileRoomName(this.workspace, relativePath))}`);
    }
    return values.join('&');
  }

  private getApiUrl(endpoint: string): string {
    const httpUrl = normalizeServerUrl(this.serverUrl).replace(/^ws/i, 'http');
    return `${httpUrl}/api${endpoint}`;
  }

  private async getRemoteManifest(): Promise<FileManifest> {
    const url = `${this.getApiUrl('/manifest')}?${this.getQuery()}`;
    const res = await requestUrl({ url, method: 'GET' });
    if (res.status !== 200) throw new Error(`Server returned HTTP ${res.status}: ${res.text || 'No response body'}`);
    return res.json as FileManifest;
  }

  private async uploadFile(relativePath: string, data: ArrayBuffer, mtime: number) {
    const url = `${this.getApiUrl('/upload')}?${this.getQuery(relativePath)}&mtime=${mtime}`;
    const res = await requestUrl({
      url,
      method: 'POST',
      body: data,
    });
    if (res.status !== 200) throw new Error(`Upload failed: ${res.text}`);
  }

  private async downloadFile(relativePath: string): Promise<ArrayBuffer> {
    const url = `${this.getApiUrl('/download')}?${this.getQuery(relativePath)}`;
    const res = await requestUrl({ url, method: 'GET' });
    if (res.status !== 200) throw new Error('Download failed');
    return res.arrayBuffer;
  }

  public async deleteRemoteFile(relativePath: string) {
    if (shouldIgnore(relativePath)) return;
    try {
      const url = `${this.getApiUrl('/delete')}?${this.getQuery(relativePath)}`;
      await requestUrl({ url, method: 'DELETE' });
    } catch (e) {
      console.warn(`[LaplasCowork] Failed to delete remote file ${relativePath}:`, e);
    }
  }

  /**
   * Writes binary data directly to the Obsidian vault using low-level adapter APIs 
   * to bypass standard hidden-file limitations of app.vault.
   */
  private async writeToVaultUI(relPath: string, data: ArrayBuffer) {
    await this.app.vault.adapter.writeBinary(relPath, data);
  }

  private async hashData(data: ArrayBuffer): Promise<string> {
    const digest = await globalThis.crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('');
  }

  private get syncScope(): string {
    return `${normalizeServerUrl(this.serverUrl)}|${(this.workspace || 'default-workspace').trim() || 'default-workspace'}`;
  }

  private loadSyncState(): Promise<void> {
    return this.syncStateLoadPromise ??= this.readSyncState();
  }

  private async readSyncState() {
    const statePath = `${this.dataDir}/sync-state.json`;
    try {
      if (await this.app.vault.adapter.exists(statePath)) {
        this.syncState = JSON.parse(await this.app.vault.adapter.read(statePath));
      }
    } catch (error) {
      console.warn('[LaplasCowork] Could not load sync state; rebuilding it from hashes.', error);
      this.syncState = {};
    }

    const legacyPath = `${this.app.vault.configDir}/plugins/live-cursor/data/sync-state.json`;
    try {
      if (legacyPath !== statePath && await this.app.vault.adapter.exists(legacyPath)) {
        const legacyState = JSON.parse(await this.app.vault.adapter.read(legacyPath)) as Record<string, Record<string, string>>;
        for (const [scope, files] of Object.entries(legacyState)) {
          const currentFiles = this.syncState[scope] ?? (this.syncState[scope] = {});
          for (const [path, hash] of Object.entries(files)) {
            if (currentFiles[path] === undefined) {
              currentFiles[path] = hash;
              this.syncStateDirty = true;
            }
          }
        }
      }
    } catch (error) {
      console.warn('[LaplasCowork] Could not migrate legacy sync state.', error);
    }
  }

  private getFileSyncState(path: string): string | undefined {
    const normalized = this.syncState[this.syncScope]?.[path];
    if (normalized !== undefined) return normalized;
    const legacy = this.syncState[`${this.serverUrl.trim()}|${this.workspace}`]?.[path];
    if (legacy !== undefined) return legacy;

    const workspaceSuffix = `|${(this.workspace || 'default-workspace').trim() || 'default-workspace'}`;
    for (const [scope, files] of Object.entries(this.syncState)) {
      if (
        scope.endsWith(workspaceSuffix) &&
        normalizeServerUrl(scope.slice(0, -workspaceSuffix.length)) === normalizeServerUrl(this.serverUrl) &&
        files[path] !== undefined
      ) {
        return files[path];
      }
    }
    return undefined;
  }

  private setFileSyncState(path: string, hash: string) {
    const scope = this.syncScope;
    const state = this.syncState[scope] ?? (this.syncState[scope] = {});
    if (state[path] === hash) return;
    state[path] = hash;
    this.syncStateDirty = true;
  }

  private saveSyncState(): Promise<void> {
    const save = this.syncStateSavePromise.then(async () => {
      if (!this.syncStateDirty) return;
      const serialized = JSON.stringify(this.syncState);
      this.syncStateDirty = false;
      try {
        await this.app.vault.adapter.mkdir(this.dataDir).catch(() => {});
        await this.app.vault.adapter.write(`${this.dataDir}/sync-state.json`, serialized);
      } catch (error) {
        this.syncStateDirty = true;
        throw error;
      }
    });
    this.syncStateSavePromise = save.catch(() => {});
    return save;
  }

  public async getLastSyncedHash(path: string): Promise<string | undefined> {
    await this.loadSyncState();
    return this.getFileSyncState(path);
  }

  public async recordSyncedHash(path: string, hash: string): Promise<void> {
    await this.loadSyncState();
    this.setFileSyncState(path, hash);
    await this.saveSyncState();
  }

  public hashText(text: string): Promise<string> {
    return this.hashData(new TextEncoder().encode(text).buffer as ArrayBuffer);
  }

  private async removeLocalFile(path: string) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof TFile) await this.app.vault.delete(file);
    else await this.app.vault.adapter.remove(path);
  }

  private async preserveConflict(path: string, data: ArrayBuffer, source: string) {
    if (!path.endsWith('.md')) return;
    const safeSource = source.replace(/[\\/:*?"<>|]/g, '-');
    const hash = await this.hashData(data);
    let conflictPath = this.getConflictPath(path, `${safeSource} ${hash.slice(0, 12)}`);
    if (await this.app.vault.adapter.exists(conflictPath)) {
      const existingHash = await this.hashData(await this.app.vault.adapter.readBinary(conflictPath));
      if (existingHash === hash) return;
      conflictPath = this.getConflictPath(path, `${safeSource} ${hash}`);
      if (await this.app.vault.adapter.exists(conflictPath)) {
        const fullHash = await this.hashData(await this.app.vault.adapter.readBinary(conflictPath));
        if (fullHash === hash) return;
        conflictPath = this.getConflictPath(path, `${safeSource} ${hash} ${Date.now()}`);
      }
    }
    await this.ensureDirExists(conflictPath, '');
    await this.writeToVaultUI(conflictPath, data);
  }

  private getConflictPath(path: string, deviceName: string): string {
    const normalized = path.replace(/\\/g, '/');
    const idx = normalized.lastIndexOf('.');
    if (idx !== -1 && idx > normalized.lastIndexOf('/')) {
      return normalized.substring(0, idx) + ` (Conflict from ${deviceName})` + normalized.substring(idx);
    }
    return normalized + ` (Conflict from ${deviceName})`;
  }

  /**
   * Ensures parent directories exist recursively using the raw file system adapter.
   */
  private async ensureDirExists(relPath: string, configDir: string) {
    const normalized = relPath.replace(/\\/g, '/');
    const parts = normalized.split('/');
    let cur = configDir;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i] as string;
      cur = cur ? cur + '/' + part : part;
      const exists = await this.app.vault.adapter.exists(cur);
      if (!exists) {
        await this.app.vault.adapter.mkdir(cur).catch(() => {});
      }
    }
  }

  /**
   * Performs an incremental, database-free whole-vault configuration and file sync.
   * Compares the local file system manifest with the server manifest, pushing and pulling 
   * updates as needed, and resolving conflicts automatically.
   */
  public async syncConfig(silent: boolean = false) {
    if (this.isSyncing) {
      this.syncPending = true;
      if (!silent) new Notice('Sync already in progress...');
      return;
    }
    this.isSyncing = true;
    if (!silent) new Notice('Syncing vault files...', 2000);

    try {
      await this.loadSyncState();
      const remoteManifest = await this.getRemoteManifest();
      const localFiles: { path: string, stat: any }[] = [];

      // Recursive local scan starting from the vault root ""
      const scanDir = async (dir: string) => {
        if (shouldIgnore(dir)) return;

        const list = await this.app.vault.adapter.list(dir);
        for (const file of list.files) {
          if (shouldIgnore(file)) continue;
          const stat = await this.app.vault.adapter.stat(file);
          if (stat) localFiles.push({ path: file, stat });
        }
        for (const folder of list.folders) {
          await scanDir(folder);
        }
      };

      await scanDir("");

      // Map local files by relative path for unified syncing
      const localMap = new Map<string, { path: string, stat: any }>();
      for (const local of localFiles) {
        const relPath = local.path.replace(/\\/g, '/');
        localMap.set(relPath, local);
      }

      // Collect all unique relative paths across local and remote
      const allPaths = new Set<string>([
        ...localMap.keys(),
        ...Object.keys(remoteManifest)
      ]);

      let actionsCount = 0;

      for (const relPath of allPaths) {
        const local = localMap.get(relPath);
        const remote = remoteManifest[relPath];

        // Active markdown files belong exclusively to their Yjs room. A
        // tombstone is still handled so a remote deletion cannot be revived by
        // an automatically reconnecting WebSocket client.
        if (this.isLivePath(relPath) && !remote?.deleted) continue;

        if (remote?.deleted) {
          const deletedState = `!${remote.hash || ''}`;
          if (local) {
            const localData = await this.app.vault.adapter.readBinary(local.path);
            const localHash = await this.hashData(localData);
            const previousHash = this.getFileSyncState(relPath);
            const alreadyObservedDeletion = previousHash?.startsWith('!');
            const unchangedSinceSync = previousHash === localHash || localHash === remote.hash;
            if (!alreadyObservedDeletion && (!remote.hash || unchangedSinceSync)) {
              await this.removeLocalFile(local.path);
              this.setFileSyncState(relPath, deletedState);
            } else {
              await this.uploadFile(relPath, localData, local.stat.mtime);
              this.setFileSyncState(relPath, localHash);
            }
            actionsCount++;
          } else {
            this.setFileSyncState(relPath, deletedState);
          }
          continue;
        }

        if (local && !remote) {
          // File exists only locally -> Upload
          const data = await this.app.vault.adapter.readBinary(local.path);
          await this.uploadFile(relPath, data, local.stat.mtime);
          this.setFileSyncState(relPath, await this.hashData(data));
          actionsCount++;
        } else if (!local && remote) {
          // File exists only remotely -> Download
          await this.ensureDirExists(relPath, '');
          const data = await this.downloadFile(relPath);
          await this.writeToVaultUI(relPath, data);
          this.setFileSyncState(relPath, remote.hash ?? await this.hashData(data));
          actionsCount++;
        } else if (local && remote) {
          const localData = await this.app.vault.adapter.readBinary(local.path);
          const localHash = await this.hashData(localData);
          if (remote.hash === localHash) {
            this.setFileSyncState(relPath, localHash);
            continue;
          }

          const remoteData = await this.downloadFile(relPath);
          const remoteHash = remote.hash ?? await this.hashData(remoteData);
          if (remoteHash === localHash) {
            this.setFileSyncState(relPath, localHash);
            continue;
          }

          const decision = decideSyncAction(this.getFileSyncState(relPath), localHash, remoteHash);

          if (decision === 'upload') {
            await this.uploadFile(relPath, localData, local.stat.mtime);
            this.setFileSyncState(relPath, localHash);
          } else if (decision === 'download') {
            await this.writeToVaultUI(relPath, remoteData);
            this.setFileSyncState(relPath, remoteHash);
          } else if (relPath.endsWith('.md')) {
            await this.preserveConflict(relPath, localData, this.deviceName);
            await this.writeToVaultUI(relPath, remoteData);
            this.setFileSyncState(relPath, remoteHash);
          } else if (local.stat.mtime > remote.mtime) {
            await this.uploadFile(relPath, localData, local.stat.mtime);
            this.setFileSyncState(relPath, localHash);
          } else {
            await this.writeToVaultUI(relPath, remoteData);
            this.setFileSyncState(relPath, remoteHash);
          }
          actionsCount++;
        }
      }

      if (!silent) new Notice(actionsCount > 0 ? `Sync complete (${actionsCount} updated)` : 'Vault in sync.', 2000);
    } catch (e: any) {
      console.error('[LaplasCowork] Sync Error:', e);
      if (!silent) {
        const errMsg = e.message || String(e);
        new Notice(`Sync failed: ${errMsg}`, 5000);
      }
    } finally {
      await this.saveSyncState().catch(error => {
        console.error('[LaplasCowork] Failed to save sync state:', error);
      });
      this.isSyncing = false;
      if (this.syncPending) {
        this.syncPending = false;
        void this.syncConfig(true);
      }
    }
  }
}
