import esbuild from "esbuild";
import process from "process";
import path from "node:path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const embeddedServerPlugin = {
	name: "embedded-sync-server",
	setup(build) {
		build.onResolve({ filter: /^\.\/server\.js\?embedded$/ }, args => ({
			path: path.resolve(args.resolveDir, "server.js"),
			namespace: "embedded-sync-server",
		}));

		build.onLoad({ filter: /.*/, namespace: "embedded-sync-server" }, async args => {
			const result = await esbuild.build({
				entryPoints: [args.path],
				bundle: true,
				platform: "node",
				format: "cjs",
				target: "node18",
				write: false,
				logLevel: "silent",
			});
			const source = result.outputFiles[0].text;
			return {
				contents: `export default ${JSON.stringify(source)};`,
				loader: "js",
				watchFiles: [args.path],
			};
		});
	},
};

const clientContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	plugins: [embeddedServerPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"child_process",
		"fs",
		"path",
		"os",
		"crypto",
		"net",
		"tls",
		"http",
		"https",
		"zlib",
		"url"
	],
	alias: {
		"process": "process",
		"buffer": "buffer",
		"events": "events",
		"stream": "stream-browserify",
		"util": "util"
	},
	inject: ["./process-shim.js"],
	define: {
		"process.env.NODE_ENV": '"production"',
		"global": "window"
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await clientContext.rebuild();
	await clientContext.dispose();
	process.exit(0);
} else {
	await clientContext.watch();
}
