import esbuild from "esbuild";
import process from "process";
import { builtinModules, createRequire } from "module";

const require = createRequire(import.meta.url);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const clientContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"child_process",
		"fs",
		"path",
		"os",
		"crypto",
		"net",
		"tls",
		"http",
		"https",
		"zlib",
		"url"
	],
	alias: {
		"process": "process",
		"buffer": "buffer",
		"events": "events",
		"stream": "stream-browserify",
		"util": "util"
	},
	inject: ["./process-shim.js"],
	define: {
		"process.env.NODE_ENV": '"production"',
		"global": "window"
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

const serverContext = await esbuild.context({
	entryPoints: ["server.js"],
	bundle: true,
	platform: "node",
	format: "cjs",
	target: "node18",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outfile: "server.bundle.js",
});

if (prod) {
	await Promise.all([clientContext.rebuild(), serverContext.rebuild()]);
	await Promise.all([clientContext.dispose(), serverContext.dispose()]);
	process.exit(0);
} else {
	await Promise.all([clientContext.watch(), serverContext.watch()]);
}
